### ISSUE TITLE
Undefined variable: write 

### ISSUE THREAD

**Issue by robert1112** [soulseekah/hyperdb-mysqli#10]
Hi 

I got the error below on a Wordpress site. After removing write variable, the error shown on debug mode are fixed. It also actually cause the problem on Woocommerce checkout page. It just continue loading. Please kindly advice where to check. Thank you.

```
Notice: Undefined variable: write in /var/www/blog/wp-content/db.php on line 570
Notice: Undefined variable: write in /var/www/blog/wp-content/db.php on line 606
```

Site Info
```
WC version:		3.3.5
WP version:		4.9.5
Server info:		Apache/2.4.10 (Debian)
PHP version:		7.1.16
```

**Comment by pinheiroalexandre2** [comment]
@robert1112
I have exactly same problem.
Do you any fix for this?

**Comment by soulseekah** [comment]
Support for mysqli is finally mainline https://wordpress.org/plugins/hyperdb/
My plugin is of no use now.
