### ISSUE TITLE
Sessions being kicked out

### ISSUE THREAD

**Issue by shadezero** [soulseekah/hyperdb-mysqli#2]
Hi,

For some reason sessions are being disconnected randomly when this plugin is enabled.

**Comment by soulseekah** [comment]
Anything in the error logs? What version of MySQL? What version of PHP?

**Comment by shadezero** [comment]
Sever: Microsoft 2012 R2 -  IIS 8.5
PHP: 7.0 with WinCache
MySQL Server Versions: 5.5.44 | 5.5.5-10.0.23 | 5.5.44

Checking Logs

**Comment by soulseekah** [comment]
Thanks. If there's nothing in the logs, how do you know the sessions are disconnected?

Also, I assume you're referring to sessions as in database connection sessions, right?

**Comment by shadezero** [comment]
I'm going over the MariaDB Binary logs at the moment.
I've tried this on 2 different IIS servers, and it's happened on all sites that utilize this plugin.

Essentially, it takes 4 or 5 tries for it to write to the database.  The login prompt appears after a few minutes of idle or browsing around in /wp-admin/

I'm referring to the wp-admin sessions.

**Comment by soulseekah** [comment]
What are the errors for the write tries?

**Comment by shadezero** [comment]
The issue isn't only when there are writes happening.
Just sitting around in /wp-admin/ causes it.  

If I leave it idling - I'll see the WP-Login overlay quickly appear and disappear (as if I just logged in).

If you like, I can PM you directly and give you access to a site where it is happening.

**Comment by soulseekah** [comment]
Support for mysqli is finally mainline https://wordpress.org/plugins/hyperdb/
My plugin is of no use now.
