### ISSUE TITLE
boolean results give fatal error

### ISSUE THREAD

**Issue by untoreh** [soulseekah/hyperdb-mysqli#3]
I added this

```
if(gettype($this->result) == 'boolean') return $this->result;
```

in the `mysqli_query` in the `query()` function to return the query, otherwise `mysqli_num_fields` tries to process a boolean value and gives fatal.

**Comment by soulseekah** [comment]
What's the test case, please?

**Comment by natostanco** [comment]
```
SELECT SQL_CALC_FOUND_ROWS  nt_posts.BLOG_ID, nt_posts.ID FROM nt_posts  WHERE 1=1  AND (nt_posts.BLOG_ID != 53) AND nt_posts.post_type IN ('post') AND (nt_posts.post_status = 'publish')  ORDER BY FIELD( nt_posts.ID, ) ASC LIMIT 0, 5
```

```
Stack trace:
#0 .../wp/wp-content/db.php(841): mysqli_num_fields()
#1 .../wp/wp-includes/wp-db.php(2322): hyperdb->query()
#2 .../wp/wp-content/plugins/plugin/plugin.php(2699): wpdb->get_results()
```

**Comment by natostanco** [comment]
ehr...it should be added as an `OR` statement a few lines down
`		if ( preg_match("/^\\s*(insert|delete|update|replace|alter) /i",$query) || gettype($this->result) == 'boolean' ) {
`

**Comment by soulseekah** [comment]
Support for mysqli is finally mainline https://wordpress.org/plugins/hyperdb/
My plugin is of no use now.
