### ISSUE TITLE
Needs support for utf8mb4 charset

### ISSUE THREAD

**Issue by cyruscollier** [soulseekah/hyperdb-mysqli#6]
Currently, you cannot use this with newer versions of WordPress without modifying this drop-in, as it blocks all charsets that are not utf8 or latin1. WordPress uses uft8mb4 now.

**Comment by soulseekah** [comment]
Pretty sure that `DB_COLLATE` and `DB_CHARSET` are obeyed as necessary.

https://github.com/soulseekah/hyperdb-mysqli/blob/master/db.php#L195-L211

Let me know how exactly the charsets are "blocked"?

**Comment by cyruscollier** [comment]
Right here:

https://github.com/soulseekah/hyperdb-mysqli/blob/master/db.php#L714-L715

I don't really see a reason for these lines at all, but it should at least be updated to include utf8mb4 in the list of allowed charsets.

**Comment by soulseekah** [comment]
I see what you mean. Feel free to send in a pull request and I'll merge. Thanks.
